name: flashlearn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0
  staggered_grid_view_flutter: ^0.0.4
  flip_card: ^0.7.0
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
