name: flashlearn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0
  staggered_grid_view_flutter: ^0.0.4
  flip_card: ^0.7.0
  curved_navigation_bar: ^1.0.6
  pie_chart: ^5.4.0
  fl_chart: ^0.68.0
  json_annotation: ^4.9.0
  vertical_card_pager: ^1.6.2
  image_picker: ^1.1.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/front1.png
    - assets/images/front2.png
    - assets/images/front3.png
    - assets/images/back.png
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf

